name = "TFL Cogs N Worlds"
author = "Liz. C"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b064ec634dc4d9a39b1aca8583470b37d513efd983600faf3324f0fbb1b8f0a4"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
