name = "TFL Cogs N Worlds"
author = "Liz. C"
version = "1.0.1-a.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74aaefd5fed672ca12af68632ef812ce8badfbdab8b3111730c040c1908a3576"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
