name = "TFL Cogs N Worlds"
author = "Liz. C"
version = "1.0.1-a.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "668ca17797715a5dd3a1b6959387857dc90f647ec009c5a9a84e75924cede314"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
