name = "TFL Cogs N Worlds"
author = "Liz. C"
version = "1.0.1-a.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff709c9c75ae7c6c12fd2ac1060df1f1a89345cf5dfeaeab4afa20ed3b1bcf4c"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
